# Generated by Django 6.0.3 on 2026-04-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_password_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
