"""
Django settings for Online_Quiz_Core project.

Настройки конфигурации проекта онлайн-викторины, включая параметры безопасности,
подключение приложений, базы данных, статических файлов, email и интеграцию с VK Bot.

Generated by 'django-admin startproject' using Django 6.0.3.
For more information, see https://docs.djangoproject.com/en/6.0/topics/settings/
"""

import os
from pathlib import Path

from environs import Env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
env = Env()
env.read_env(BASE_DIR / ".env")

SECRET_KEY = env.str("SECRET_KEY_DJANGO")
DEBUG = env.bool("DEBUG", default=True)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=['localhost', '127.0.0.1', '0.0.0.0'])

# Application definition
INSTALLED_APPS = [
    'channels',
    'daphne',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'users',
    'game_quiz',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Online_Quiz_Core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'Online_Quiz_Core.asgi.application'
WSGI_APPLICATION = 'Online_Quiz_Core.wsgi.application'

# Channel Layers
# Настройка Redis для работы WebSocket каналов в реальном времени
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    }
}

REDIS_TTL = 7200  # Время жизни данных в Redis (в секундах)

# Database
# Настройка подключения к PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env.str("DB_NAME"),
        'USER': env.str("DB_USER"),
        'PASSWORD': env.str("DB_PASSWORD"),
        'HOST': env.str("DB_HOST"),
        'PORT': env.str("DB_PORT"),
    }
}

# Password validation
# Валидаторы паролей для обеспечения безопасности учетных записей
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Sessions & Auth
# Настройки сессий: время жизни, безопасность, SameSite для защиты от CSRF
SESSION_COOKIE_AGE = 1209600
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

LOGIN_REDIRECT_URL = 'main:index'
LOGIN_URL = 'users:login'
LOGOUT_REDIRECT_URL = 'main:index'

# Email (Mail.ru SMTP)
# Конфигурация SMTP-сервера для отправки уведомлений пользователям
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mail.ru'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env.str("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Logging for Channels & Daphne
# Настройка логгирования для отладки WebSocket соединений
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'channels': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'daphne': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# VK Bot settings
VK_BOT_TOKEN = env.str("VK_BOT_TOKEN", default="")

# Django API URL (для бота)
DJANGO_API_URL = env.str("DJANGO_API_URL", default="http://127.0.0.1:8000")

# Стили админки Jazzmin
JAZZMIN_SETTINGS = {
    "site_title": "Онлайн-Викторина",
    "site_header": "Викторина Admin",
    "site_brand": "Управление Игрой",
    "welcome_sign": "Добро пожаловать в панель управления",
    "search_model": ["auth.User", "game_quiz.QuizGame"],
    "show_ui_builder": False,
    "topmenu_links": [
        {"name": "Главная сайта", "url": "/", "permissions": ["auth.view_user"]},
    ],
    "icons": {
        "auth.User": "fas fa-users",
        "users.UserProfile": "fas fa-id-card",
        "users.UserRole": "fas fa-user-shield",
        "game_quiz.QuizGame": "fas fa-gamepad",
        "game_quiz.QuizQuestionSet": "fas fa-question-circle",
        "game_quiz.GameResult": "fas fa-trophy",
    },
}
