# Generated by Django 6.0.3 on 2026-04-24 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название набора')),
                ('quiz_set_content', models.JSONField(default=list, verbose_name='Вопросы')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный набор')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Набор вопросов',
                'verbose_name_plural': 'Наборы вопросов',
            },
        ),
    ]
