# Generated by Django 6.0.3 on 2026-05-03 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник игры',
                'verbose_name_plural': 'Участники игр',
            },
        ),
        migrations.CreateModel(
            name='QuizGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название викторины')),
                ('game_code', models.CharField(db_index=True, max_length=8, unique=True, verbose_name='Код комнаты')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание игроков'), ('playing', 'Игра идёт'), ('finished', 'Игра завершена')], default='waiting', verbose_name='Статус игры')),
                ('is_public', models.BooleanField(default=False, verbose_name='Доступность игры')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_games', to=settings.AUTH_USER_MODEL, verbose_name='Ведущий викторины')),
                ('participants', models.ManyToManyField(blank=True, related_name='played_games', through='game_quiz.GameParticipant', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Игровая сессия',
                'verbose_name_plural': 'Игровые сессии',
            },
        ),
        migrations.AddField(
            model_name='gameparticipant',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_quiz.quizgame'),
        ),
        migrations.CreateModel(
            name='QuizQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название набора')),
                ('quiz_set_content', models.JSONField(default=list, verbose_name='Вопросы')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный набор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sets', to=settings.AUTH_USER_MODEL, verbose_name='Автор набора')),
            ],
            options={
                'verbose_name': 'Набор вопросов',
                'verbose_name_plural': 'Наборы вопросов',
            },
        ),
        migrations.AddField(
            model_name='quizgame',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='game_quiz.quizquestionset', verbose_name='Набор вопросов'),
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Очки')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Место в игре')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_results', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game_quiz.quizgame')),
            ],
            options={
                'verbose_name': 'Результат игры',
                'verbose_name_plural': 'Результаты игр',
                'unique_together': {('game', 'player')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='gameparticipant',
            unique_together={('game', 'player')},
        ),
    ]
