# Generated by Django 6.0.3 on 2026-05-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_quiz', '0003_remove_gameresult_correct_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0, verbose_name='Правильных ответов'),
        ),
    ]
