# Generated by Django 6.0.3 on 2026-05-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_quiz', '0004_gameresult_correct_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresult',
            name='correct_answers',
        ),
    ]
