# Generated by Django 6.0.3 on 2026-05-22 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_quiz', '0006_alter_gameparticipant_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizgame',
            name='question_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='game_quiz.quizquestionset', verbose_name='Набор вопросов'),
        ),
    ]
